version: "3.7"
services:
  flask_app:
    build: './flask_app'
    environment:
      - REDIS_URL=redis
      - REDIS_PORT=6379
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
    ports:
      - "5000:5000"
    depends_on:
      - redis

  simple_worker:
    build: './simple_worker'
    user: nobody
    depends_on:
      - redis
      - flask_app


  redis:
    image: 'redis:4-alpine'
    ports:
      - '6379:6379'
